### PR TITLE
fix: return correct neonctl version

### LINKED ISSUE #196: Version reported as `unknown` at least on 1.28.0 on Linux x64
## Steps to reproduce
Run `neonctl -v`

## Expected result
Something along the lines of:
```
❯ neonctl -v
1.28.0
```
## Actual result
```
❯ neonctl -v
unknown
```

## Environment
- Fedora 39 x64
- Node 20.9.0

I haven't tested the other builds or other versions to see if this is just an issue with 1.28.0

### PR DESCRIPTION
**Pull request by mrl5**
closes #196

### CODE REVIEW

**Comment by duskpoet** [comment]
Nice, thanks!

**Review by duskpoet — APPROVED** [review]

**Comment by mrl5** [comment]
BTW, I tested it by replacing `node_modules/neonctl/index.js` (installed in some other directory) with the fixed one that was produced by `bun run build` (`dist/index.js`)

**Comment by duskpoet** [comment]
Is it ok to merge?

**Comment by mrl5** [comment]
from my perspective it is ready and ok to be merged.

I marked it as draft for a while because there was a regression -- `neonct -v` was not working, but I only had to reorder new line and put it above `.group()`

**Pull request merged**
